## Numpy

In [4]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [5]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [6]:
%timeit [x**2 for x in big_list]

14 ms ± 3.68 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%timeit big_array ** 2 

132 μs ± 30.9 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
### Creating arrays

In [10]:
a = np.array([1,2,3,4])  # ONE DIMENSIOANAL ARRAY (1-D)
print(a)


[1 2 3 4]


In [12]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #TWO DIMENSIOANAL ARRAY (2-D)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [15]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [18]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [19]:
print(np.eye(3)) #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
rng = np.random.default_rng(seed=42) # random number
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [28]:
print(rng.integers(1,10,size=(3,3))) #uniform

[[5 3 1]
 [5 8 1]
 [8 8 3]]


In [31]:
print(rng.normal(loc=0, scale = 1, size = 5))

[ 2.1416476  -0.40641502 -0.51224273 -0.81377273  0.61597942]


In [33]:
## arrays attributes and data types

In [35]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(m.ndim)

2


In [37]:
print(m.shape)

(2, 3)


In [38]:
print(m.size)

6


In [39]:
print(m.size)

6


In [42]:
print(m.dtype)

int64


In [45]:
ints = np.array([1,2,3], dtype=np.int32)

In [46]:
ints.dtype

dtype('int32')

In [48]:
floats = np.array([1,2,3], dtype=np.float64)
floats.dtype

dtype('float64')

In [49]:
# indexing and slicing

In [50]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
print([0])

[0]


In [52]:
print([5])

[5]


In [57]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
print(M[1,2])

7


In [61]:
print(M[0])
print(M[1])


[1 2 3 4]
[5 6 7 8]


In [62]:
print(M[:,0])

[1 5 9]


In [63]:
## vector operation

In [64]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [67]:
print(a) 
print(b) 



[1 2 3 4]
[10 20 30 40]


In [68]:
print(a+b) 

[11 22 33 44]


In [69]:
print(a*b)

[ 10  40  90 160]


In [70]:
# Broadcasting

In [71]:
a = np.array([1,2,3])
b = 10

In [72]:
print(a+b)

[11 12 13]


In [73]:
a = np.array([[1,2,3]
            ,[4,5,6]
             ])
a.shape

(2, 3)

In [74]:
b = np.array([10,20,30])
b.shape

(3,)

In [75]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [78]:
a = np.array([[1,2]
            ,[3,4]
             ])
a.shape

(2, 2)

In [79]:
b = np.array([10,20,30])
b.shape


(3,)